#!/usr/bin/env php
<?php

namespace SunCoastConnection\ClaimsToOEMR;

use \ErrorException,
	\SunCoastConnection\ClaimsToOEMR\Document\Options,
	\SunCoastConnection\ClaimsToOEMR\Document\Raw,
	\SunCoastConnection\ClaimsToOEMR\Store,
	\SunCoastConnection\ClaimsToOEMR\X12N837,
	\SunCoastConnection\ClaimsToOEMR\X12N837\Cache,
	\Symfony\Component\Finder\Finder;


set_error_handler(__NAMESPACE__.'\exceptions_error_handler');

echo 'Setting up autoloading...'.PHP_EOL;

//** LOAD AUTOLOADER **//
$autoload = include(__DIR__.'/vendor/autoload.php');

if($autoload == false) {
	is_dir(dirname($autoloadPath)) || exitError(
		'Application has not been installed correctly.'.PHP_EOL.
			'Navigate to: '.__DIR__.PHP_EOL.
			'Run: composer install --no-dev'.PHP_EOL,
		1
	);

	file_exists($autoloadPath) || exitError(
		'Autoload component is missing: '.$autoloadPath.PHP_EOL,
		1
	);

	is_readable($autoloadPath) || exitError(
		'Autoload component is not readable: '.$autoloadPath.PHP_EOL,
		1
	);
}

echo 'Loading configurations...'.PHP_EOL;

//** GET CONFIGURATION OPTIONS **//
$options = Options::getInstance(require_once(__DIR__.'/config/app.php'));


$cmd = array_shift($argv);
$cmdOption = array_shift($argv);

switch($cmdOption) {
	case 'migrate':
		$connection = getStoreConnection($options);
		if($connection['driver'] === 'array') {
			exitError(
				'Store driver `array` does not need to be migrated'.PHP_EOL,
				1
			);
		}

		c2eMigrate($options);
		break;

	case 'parse':
		c2eParse($options);
		break;

	default:
		exitError('Unknown option: '.$cmdOption, 1);
		break;
}

function exceptions_error_handler($severity, $message, $filename, $lineno) {
	if(error_reporting() !== 0 && (error_reporting() & $severity)) {
		throw new ErrorException($message, 0, $severity, $filename, $lineno);
	}
}

function exitError($message, $errorCode = 0) {
	echo $message;
	exit($errorCode);
}

function getStoreConnection($options, $connection = null) {
	if(is_null($connection)) {
		$connection = $options->get('Store.default', 'array');
	}

	return $options->get('Store.connections.'.$connection, 'array');
}

function setupStore($options) {
	$connection = getStoreConnection($options);

	if($connection['driver'] === 'array') {
		$store = Store\Arr::getInstance($options);
	} else {
		if($connection['driver'] === 'sqlite' && !file_exists($connection['database'])) {
			touch($connection['database']) || exitError(
				'SQLite database missing and can not be created: '.$connection['database'].PHP_EOL,
				1
			);
		}

		$store = Store\Database::getInstance($options);
	}

	$options->set('App.store', $store);
}

function c2eMigrate($options) {
	setupStore($options);

	include(__DIR__.'/database/migrate.php');
}

function c2eParse($options) {
	$inboxPath		= $options->get('Inbox.path');
	$inboxPattern	= $options->get('Inbox.pattern');

	$finder = new Finder;
	$finder->files()
		->in($inboxPath)
		->name($inboxPattern)
		->sortByName();

	if($options->get('Inbox.recursive') == false) {
		$finder->depth('== 0');
	}

	setupStore($options);

	echo 'Initial store record counts:'.PHP_EOL.PHP_EOL;

	$options->get('App.store')->printTableCounts();

	echo PHP_EOL;

	echo 'Found '.$finder->count().' file(s) in directory: '.realpath($inboxPath).PHP_EOL.PHP_EOL;

	foreach($finder as $file) {
		echo " - Filename:\t\t".$file->getRealpath().PHP_EOL;
		echo " - Filesize:\t\t".$file->getSize().PHP_EOL;

		c2eClaimLoad($options, $file);
	}
}

function c2eClaimLoad($options, $file) {
	$raw = Raw::getInstance($options);
	$raw->parse($file->getContents());

	$document = X12N837::getInstance($options);
	$document->parse($raw);

	c2eClaimCache($options, $document);
}

function c2eClaimCache($options, $document) {
	$cache = Cache::getInstance($options->get('App.store'));

	$cache->processDocument($document);

	$options->get('App.store')->printTableCounts();

	echo PHP_EOL;
}