#!/usr/bin/env php
<?php

namespace SunCoastConnection\ClaimsToEMR;

use \ErrorException;
use \SunCoastConnection\ClaimsToEMR\Store\Database;
use \SunCoastConnection\ClaimsToEMR\X12N837;
use \SunCoastConnection\ParseX12\Options;
use \Symfony\Component\Finder\Finder;

set_error_handler(__NAMESPACE__.'\exceptions_error_handler');

//** LOAD AUTOLOADER **//
$autoload = include(__DIR__.'/vendor/autoload.php');

if($autoload == false) {
	is_dir(dirname($autoloadPath)) || exitError(
		'Application has not been installed correctly.'.PHP_EOL.
			'Navigate to: '.__DIR__.PHP_EOL.
			'Run: composer install --no-dev',
		1
	);

	file_exists($autoloadPath) || exitError(
		'Autoload component is missing: '.$autoloadPath,
		1
	);

	is_readable($autoloadPath) || exitError(
		'Autoload component is not readable: '.$autoloadPath,
		1
	);
}

echo 'Loading configurations...'.PHP_EOL;
$options = Options::getInstance(require_once(__DIR__.'/config/app.php'));


$cmd = array_shift($argv);
$cmdOption = array_shift($argv);

switch($cmdOption) {
	case 'migrate':
		setupStore($options);
		c2eMigrate($options);
		break;

	case 'store-count':
		setupStore($options);
		c2eStoreCount($options);
		break;

	case 'process':
		setupStore($options);
		c2eProcess($options);
		break;

	default:
		exitError('Unknown option: '.$cmdOption, 1);
		break;
}

function exceptions_error_handler($severity, $message, $filename, $lineno) {
	if(error_reporting() !== 0 && (error_reporting() & $severity)) {
		throw new ErrorException($message, 0, $severity, $filename, $lineno);
	}
}

function exitError($message, $errorCode = 0) {
	echo $message.PHP_EOL;
	exit($errorCode);
}

function getStoreConnection($options, $connection = null) {
	if(is_null($connection)) {
		$connection = $options->get('Store.default', 'memory');
	}

	return $options->get('Store.connections.'.$connection);
}

function setupStore($options) {
	$connection = getStoreConnection($options);

	if($connection['driver'] === 'sqlite' && !file_exists($connection['database'])) {
		touch($connection['database']) || exitError(
			'SQLite database missing and can not be created: '.$connection['database'],
			1
		);
	}

	$options->set('App.store', Database::getInstance($options));
}

function c2eMigrate($options) {
	include(__DIR__.'/database/migrate.php');
}

function c2eStoreCount($options) {
	echo 'Store record counts:'.PHP_EOL.PHP_EOL;

	$options->get('App.store')->printTableCounts();

	echo PHP_EOL;
}

function c2eProcess($options) {
	$inboxPath		= $options->get('Inbox.path');
	$inboxPattern	= $options->get('Inbox.pattern');

	$finder = new Finder;
	$finder->files()
		->in($inboxPath)
		->name($inboxPattern)
		->sortByName();

	if($options->get('Inbox.recursive') == false) {
		$finder->depth('== 0');
	}

	c2eStoreCount($options);

	$fileCount = $finder->count();

	echo 'Found '.$fileCount.' file(s) in directory: '.realpath($inboxPath).PHP_EOL.PHP_EOL;

	$fileIndex = 0;

	$x12n837 = new X12N837;
	$x12n837->setOptions($options);

	foreach($finder as $file) {
		echo ' - File '.++$fileIndex.' of '.$fileCount.PHP_EOL;
		echo " - Name:\t".$file->getRealpath().PHP_EOL;
		echo " - Size:\t".$file->getSize().PHP_EOL;

		$x12n837->cacheClaim(
			$x12n837->disposeClaim(
				$x12n837->parseClaim(
					$file->getContents()
				)
			)
		);

		c2eStoreCount($options);
	}
}
