#!/usr/bin/env php
<?php

namespace SunCoastConnection\ClaimsToOEMR;

use \ErrorException,
	\SunCoastConnection\ClaimsToOEMR\Document\Options,
	\SunCoastConnection\ClaimsToOEMR\Document\Raw,
	\SunCoastConnection\ClaimsToOEMR\Store,
	\SunCoastConnection\ClaimsToOEMR\X12N837,
	\SunCoastConnection\ClaimsToOEMR\X12N837\Cache,
	\Symfony\Component\Finder\Finder;


set_error_handler(__NAMESPACE__.'\exceptions_error_handler');

function exceptions_error_handler($severity, $message, $filename, $lineno) {
	if(error_reporting() !== 0 && (error_reporting() & $severity)) {
		throw new ErrorException($message, 0, $severity, $filename, $lineno);
	}
}

function exitError($message, $errorCode = 0) {
	echo $message;
	exit($errorCode);
}

echo 'Setting up autoloading...'.PHP_EOL;

//** LOAD AUTOLOADER **//
$autoload = include(__DIR__.'/vendor/autoload.php');

if($autoload == false) {
	is_dir(dirname($autoloadPath)) || exitError(
		'Application has not been installed correctly.'.PHP_EOL.
			'Navigate to: '.__DIR__.PHP_EOL.
			'Run: composer install --no-dev'.PHP_EOL,
		1
	);

	file_exists($autoloadPath) || exitError(
		'Autoload component is missing: '.$autoloadPath.PHP_EOL,
		1
	);

	is_readable($autoloadPath) || exitError(
		'Autoload component is not readable: '.$autoloadPath.PHP_EOL,
		1
	);
}

echo 'Loading configurations...'.PHP_EOL;

//** GET CONFIGURATION OPTIONS **//
$options = Options::getNew(require_once(__DIR__.'/config/app.php'));


$cmd = array_shift($argv);
$cmdOption = array_shift($argv);

switch($cmdOption) {
	case 'migrate':
		if($options->get('Store.driver', 'array') === 'array') {
			exitError(
				'Store driver `array` does not need to be migrated'.PHP_EOL,
				1
			);
		}

		c2eMigrate($options);
		break;

	case 'parse':
		c2eParse($options);
		break;

	default:
		exitError('Unknown option: '.$cmdOption, 1);
		break;
}

function setupStore($options) {
	$driver = $options->get('Store.driver', 'array');

	if($driver === 'array') {
		$store = Store\Arr::getNew($options);
	} else {
		if($driver === 'sqlite' && !file_exists($options->get('Store.database'))) {
			touch($options->get('Store.database')) || exitError(
				'SQLite database missing and can not be created: '.$options->get('Store.database').PHP_EOL,
				1
			);
		}

		$store = Store\Database::getNew($options);
	}

	$options->set('App.store', $store);
}

function c2eMigrate($options) {
	setupStore($options);

	include(__DIR__.'/Database/migrate.php');
}

function c2eParse($options) {
	$inboxPath		= $options->get('Inbox.path');
	$inboxPattern	= $options->get('Inbox.pattern');

	$finder = new Finder;
	$finder->files()
		->in($inboxPath)
		->name($inboxPattern);

	if($options->get('Inbox.recursive') == false) {
		$finder->depth('== 0');
	}

	echo 'Found '.$finder->count().' file(s) in directory: '.realpath($inboxPath).PHP_EOL;

	foreach($finder as $file) {
		echo " - Filename:\t\t".$file->getRealpath().PHP_EOL;
		echo " - Filesize:\t\t".$file->getSize().PHP_EOL;

		c2eClaimLoad($options, $file);
	}
}

function c2eClaimLoad($options, $file) {
	$raw = Raw::getNew($options);
	$raw->parse($file->getContents());

	$document = X12N837::getNew($options);
	$document->parse($raw);

	c2eClaimCache($options, $document);
}

function c2eClaimCache($options, $document) {
	if(!$options->has('App.store')) {
		setupStore($options);

		// $options->get('App.store')->printRecordCount();
	}

	$cache = Cache::getNew($options->get('App.store'));

	$cache->processDocument($document);

	$options->get('App.store')->printRecordCount();
}