#!/usr/bin/env php
<?php

namespace SunCoastConnection\ClaimsToEMR;

// Gearman Worker Jobs

use \Kicken\Gearman\Worker;
use \Kicken\Gearman\Job\WorkerJob;
use \SunCoastConnection\ClaimsToEMR\Document\Options;
use \SunCoastConnection\ClaimsToEMR\Gearman\Job\ImportClaims;
use \SunCoastConnection\ClaimsToEMR\Gearman\Job\ReturnRemoteConnection;
use \SunCoastConnection\ClaimsToEMR\Gearman\Job\RegisterRemoteConnection;

//** LOAD AUTOLOADER **//
if(strpos(__DIR__, '/vendor/') === false) {
	require_once(__DIR__.'/vendor/autoload.php');
} else {
	require_once(substr(__DIR__, 0, strpos(__DIR__, '/vendor/') + 8).'autoload.php');
}

// Load Configurations
$options = Options::getInstance(require_once(__DIR__.'/config/gearman-worker.php'));

// Setup Gearman connection to servers
$worker = new Worker(
	$options->get('Gearman.servers', '127.0.0.1:4730')
);

// Register worker RegisterRemoteConnection
$worker->registerFunction('registerRemoteConnection',
	function(WorkerJob $job) use ($options) {
		$workerJob = RegisterRemoteConnection::getInstance($options);

		$log = [];

		$returnValue = $workerJob->run($job, $log);

		if(count($log)) {
			echo "Error:\t".implode(PHP_EOL."Error:\t", $log).PHP_EOL;
		}

		return $returnValue;
	}
);

// Register worker ReturnRemoteConnection
$worker->registerFunction('returnRemoteConnection',
	function(WorkerJob $job) use ($options) {
		$workerJob = ReturnRemoteConnection::getInstance($options);

		$log = [];

		$returnValue = $workerJob->run($job, $log);

		if(count($log)) {
			echo "Error:\t".implode(PHP_EOL."Error:\t", $log).PHP_EOL;
		}

		return $returnValue;
	}
);

// Register worker ImportClaims
$worker->registerFunction('importClaims',
	function(WorkerJob $job) use ($options) {
		$workerJob = ImportClaims::getInstance($options);

		$log = [];

		$returnValue = $workerJob->run($job, $log);

		if(count($log)) {
			echo "Error:\t".implode(PHP_EOL."Error:\t", $log).PHP_EOL;
		}

		return $returnValue;
	}
);

$worker->work();